name: Compilar y Publicar APK

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Dar permisos a Gradle
        run: chmod +x gradlew

      - name: Ejecutar compilación con Gradle
        run: ./gradlew assembleRelease

      - name: Crear Lanzamiento y Subir APK
        uses: softprops/action-gh-release@v2
        with:
          files: app/build/outputs/apk/release/app-release-unsigned.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
